Improved configuration files - init.d and nginx sample conf

diff --git a/conf/init.d.php-fpm.in b/conf/init.d.php-fpm.in
--- a/conf/init.d.php-fpm.in
+++ b/conf/init.d.php-fpm.in
@@ -1,5 +1,15 @@
 #! /bin/sh
 
+### BEGIN INIT INFO
+# Provides:          @php_fpm_bin@
+# Required-Start:    $all
+# Required-Stop:     $all
+# Default-Start:     2 3 4 5
+# Default-Stop:      0 1 6
+# Short-Description: starts @php_fpm_bin@
+# Description:       starts the PHP FastCGI Process Manager daemon
+### END INIT INFO
+
 php_fpm_BIN=@php_fpm_bin_path@
 php_fpm_CONF=@php_fpm_conf_path@
 php_fpm_PID=@php_fpm_pid_path@
@@ -39,7 +49,7 @@ wait_for_pid () {
 
 case "$1" in
 	start)
-		echo -n "Starting php_fpm "
+		echo -n "Starting @php_fpm_bin@ "
 
 		$php_fpm_BIN $php_opts
 
@@ -59,7 +69,27 @@ case "$1" in
 	;;
 
 	stop)
-		echo -n "Shutting down php_fpm "
+		echo -n "Gracefully shutting down @php_fpm_bin@ "
+
+		if [ ! -r $php_fpm_PID ] ; then
+			echo "warning, no pid file found - php-fpm is not running ?"
+			exit 1
+		fi
+
+		kill -QUIT `cat $php_fpm_PID`
+
+		wait_for_pid removed $php_fpm_PID
+
+		if [ -n "$try" ] ; then
+			echo " failed. Use force-exit"
+			exit 1
+		else
+			echo " done"
+		fi
+	;;
+
+	force-quit)
+		echo -n "Terminating @php_fpm_bin@ "
 
 		if [ ! -r $php_fpm_PID ] ; then
 			echo "warning, no pid file found - php-fpm is not running ?"
@@ -78,26 +108,6 @@ case "$1" in
 		fi
 	;;
 
-	quit)
-		echo -n "Gracefully shutting down php_fpm "
-
-		if [ ! -r $php_fpm_PID ] ; then
-			echo "warning, no pid file found - php-fpm is not running ?"
-			exit 1
-		fi
-
-		kill -QUIT `cat $php_fpm_PID`
-
-		wait_for_pid removed $php_fpm_PID
-
-		if [ -n "$try" ] ; then
-			echo " failed"
-			exit 1
-		else
-			echo " done"
-		fi
-	;;
-
 	restart)
 		$0 stop
 		$0 start
@@ -105,10 +115,10 @@ case "$1" in
 
 	reload)
 
-		echo -n "Reload service php-fpm "
+		echo -n "Reload service @php_fpm_bin@ "
 
 		if [ ! -r $php_fpm_PID ] ; then
-			echo "warning, no pid file found - php-fpm is not running ?"
+			echo "warning, no pid file found - @php_fpm_bin@ is not running ?"
 			exit 1
 		fi
 
@@ -117,22 +127,8 @@ case "$1" in
 		echo " done"
 	;;
 
-	logrotate)
-
-		echo -n "Re-opening php-fpm log file "
-
-		if [ ! -r $php_fpm_PID ] ; then
-			echo "warning, no pid file found - php-fpm is not running ?"
-			exit 1
-		fi
-
-		kill -USR1 `cat $php_fpm_PID`
-
-		echo " done"
-	;;
-
 	*)
-		echo "Usage: $0 {start|stop|quit|restart|reload|logrotate}"
+		echo "Usage: $0 {start|stop|force-quit|restart|reload}"
 		exit 1
 	;;
 
